### ISSUE TITLE
Large files and SVGs

### ISSUE THREAD

**Issue by imashnake0** [clandrew/Spritesheet2Gif#1]
Does this support SVGs? I'm trying to convert to a 60 frame gif and the app crashes. Converted to a png but to no avail. :(

**Comment by clandrew** [comment]
Thanks for getting in touch!

No, I never wrote it to support SVGs- this program doesn't have a web container or full SVG renderer. 
What version is the SVG file? If it's 1.0 and has just the [subset of elements](https://docs.microsoft.com/en-us/windows/win32/direct2d/svg-support?redirectedfrom=MSDN) supported by Direct2D, it may be possible to add support with D2D SVG and have that help.

For the large image, how big is it? I haven't personally seen any limits but the one limit that comes to mind is hardware bitmap. This program creates hardware bitmaps, so that would mean a limit of 16384 in width and in height.

**Comment by imashnake0** [comment]
Thanks for the quick reply.

[SVG version attribute deprecated?](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/version)

So that's why lol my png was 32768 x 537. The sprites were arranged in a single row which made it super wide. I did end up solving it, however. Looking forward to SVG support!

**Comment by clandrew** [comment]
For version, I don't mean the version attribute. I mean what version's features does it use. The full SVG spec, including 1.1 is insanely complicated and makes more sense for a full web browser than something for viewing a still image.

got it. Yeah I might add SVG support if i can get the time sometime. For large images, it might be possible to work around with software bitmaps but would need to see. Glad you were able to work around it.

**Comment by imashnake0** [comment]
I can't tell tbh. Is there some way to know? It's from exporting as SVG sprite sheet at [shapeshifter.design](https://shapeshifter.design/); this is a triangle, for example:

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 456 24" width="456" height="24"><path d="M5.977 8.049l13.011-.003-7.038 8.946zM29.977 8.049l13.011-.003-7.038 8.946zM53.977 8.049l13.011-.003-7.038 8.946zM77.977 8.049l13.011-.003-7.038 8.946zM101.977 8.049l13.011-.003-7.038 8.946zM125.977 8.049l13.011-.003-7.038 8.946zM149.977 8.049l13.011-.003-7.038 8.946zM173.977 8.049l13.011-.003-7.038 8.946zM197.977 8.049l13.011-.003-7.038 8.946zM221.977 8.049l13.011-.003-7.038 8.946zM245.977 8.049l13.011-.003-7.038 8.946zM269.977 8.049l13.011-.003-7.038 8.946zM293.977 8.049l13.011-.003-7.038 8.946zM317.977 8.049l13.011-.003-7.038 8.946zM341.977 8.049l13.011-.003-7.038 8.946zM365.977 8.049l13.011-.003-7.038 8.946zM389.977 8.049l13.011-.003-7.038 8.946zM413.977 8.049l13.011-.003-7.038 8.946zM437.977 8.049l13.011-.003-7.038 8.946z" fill="#000000" stroke="#000000" stroke-width=".1"/></svg>`

**Comment by clandrew** [comment]
Yeah that would work fine. When viewed with D2D SVG it looks like this: 
![image](https://user-images.githubusercontent.com/8118775/134227798-ec6b7993-a739-4bf5-9671-9401c043de64.png)

**Comment by clandrew** [comment]
The D2D doc page gives a full list if you want to check as a human, or a person can use D2D API to check programmatically. For stuff like this that's just non-animated geometry, no embedded scripts, yeah it will work,

**Comment by imashnake0** [comment]
Hey, sorry I'm not too familiar with D2D. I tried to go through the doc page but couldn't really make anything of it. I tried to upload smaller SVG sprite sheets (animated and not) and the app crashes instantly.

**Comment by clandrew** [comment]
I didn't add application support for SVG yet. 
I was talking about whether it could potentially work.

**Comment by imashnake0** [comment]
Oh, my bad. if so, I _might_ try to work on it if time permits. Either way, thanks for the app :)

**Comment by clandrew** [comment]
Sure, my pleasure! 

I started work on it with this commit: [https://github.com/clandrew/Spritesheet2Gif/commit/32863a57417ff44a42cf1c2605adfe6fce1f16d3](https://github.com/clandrew/Spritesheet2Gif/commit/32863a57417ff44a42cf1c2605adfe6fce1f16d3)

It's a good start, successfully tested it with a sample, looks like
[https://cdn.discordapp.com/attachments/798619337690841088/890859394038890516/SvgGif.gif](https://cdn.discordapp.com/attachments/798619337690841088/890859394038890516/SvgGif.gif)

Definitely welcome to some help though. This support I'm considering it 'alpha' since there are some things (svgs with no viewbox, svgs with viewbox not aligned to the top left, svgs with non-integer viewbox)  it doesn't yet handle.
